### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by monkoallday** [GDevelopApp/GDevelop-examples#107]
It is Ball Physics, Devs could use this to learn how ball physics works and use it for their next project

## Checklist

- [ y] My game has a proper name in the game properties. 
- [y ] My game package name behind with `com.example.`.
- [ No Events] My game has all events unfolded.
- [y ] I've added myself as the author in the game properties.
- [ y] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [ y] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [y ] I've cleaned unused resources.

## Game folder

<!--
Finally, attach a zip file containing your game and all its resources (images, sounds, etc...)

You also may have to create an account on GitHub before posting.
If your game is high quality and useful, it will be added to the list of GDevelop community examples.
When you're ready, remove this last paragraph and click on "Submit new issue". Thanks 🙌
--
[Ball Physics.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7193257/Ball.Physics.zip)

>

**Comment by Midhil457** [comment]
You will have to provide the zip of the project to review it

**Comment by Bouh** [comment]
No Links for the game.
