### ISSUE TITLE
Side View Zombie Horror 

### ISSUE THREAD

**Issue by bigspider95** [GDevelopApp/GDevelop-examples#111]
## Describe the example

It's a side view battle game with crawling zombie made all the assets myself, it's useful for people's who want a quick zombie template.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.

## Game folder

[Side view Horror.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7198475/Side.view.Horror.zip)

[ReadMw.md](https://github.com/GDevelopApp/GDevelop-examples/files/7198916/ReadMw.md)

**Comment by Midhil457** [comment]
Hi,
- I checked out the project a bit and I am confused to what it's supposed to do and showcase. From what I saw, it doesn't have much features that makes it a Side View Horror. The project doesn't differ much from some of the other example except for the assets
- Also, could you show from where you got the assets? (music, images)

Thanks :)

**Comment by bigspider95** [comment]
The images I made myself the music used is royalty free from soundcrate

**Comment by tristanbob** [comment]
I might be wrong, but I think the SoundCrate assets are free to use, but cannot be redistributed:
https://www.productioncrate.com/terms.html
```
Our Media Elements are strictly prohibited from use in any manner for the purpose of re-selling or distribution of our Media Elements for sale, for greenscreen only videos, or in links to downloads to any website other than Our Platform.
```
I recommend https://freepd.com/ for high-quality Public Domain music.

**Comment by Bouh** [comment]
Les visuels sont cool, mais le projet à besoin de plus de polish et de beaucoup de nettoyage.
Naming for Objects, Files, Assets, Scenes have to be changed.
Files compressed.
Crop the blank in files.
Clean unused resources.
A Readme.md
A folder with all assets inside.
A cleaning passe on the events.

**Comment by Bouh** [comment]
Hi @bigspider95
If no further changes are made within 7 days we will close this proposal for inactivity and consider this example abondonned.
