### ISSUE TITLE
Deception Must Fall Demo

### ISSUE THREAD

**Issue by bigspider95** [GDevelopApp/GDevelop-examples#112]
## Checklist

- ["Y"] My game has a proper name in the game properties. 
- ["Y"] My game package name behind with `com.example.`.
- ["Y"] My game has all events unfolded.
- ["Y"] I've added myself as the author in the game properties.
- ["Y"] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- ["Y" ] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- ["Y"
[ReadMe.md](https://github.com/GDevelopApp/GDevelop-examples/files/7198910/ReadMe.md)
 ] I've cleaned unused resources.

## Game folder

[Deception_Must_Fall10.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7198903/Deception_Must_Fall10.zip)

**Comment by Bouh** [comment]
Same, I can't open your archive, I can see the JSON file.

**Comment by Midhil457** [comment]
I was able to open the project, if it's not working for you, I can do a review (Had started one already, but didn't get the time to finish it)

**Comment by Midhil457** [comment]
I checked the project, and there are a lot of issues. As a start, please closely follow the best pratices, http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example
