### ISSUE TITLE
Alla Isometric Adventure Game

### ISSUE THREAD

**Issue by bigspider95** [GDevelopApp/GDevelop-examples#113]
## Checklist

- ["Y" ] My game has a proper name in the game properties. 
- ["Y"] My game package name behind with `com.example.`.
- ["Y"] My game has all events unfolded.
- ["Y"] I've added myself as the author in the game properties.
- ["Y"] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- ["Y"] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- ["Y"] I've cleaned unused resources.

## Game folder
[Alla Isometric Adventure Game1.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7203582/Alla.Isometric.Adventure.Game1.zip)
[ReadMe.md](https://github.com/GDevelopApp/GDevelop-examples/files/7203590/ReadMe.md)

**Comment by Midhil457** [comment]
You will have to provide the zip of the project for review

**Comment by Bouh** [comment]
The archive is corrupted I can't open it.
