### ISSUE TITLE
Tower defense example

### ISSUE THREAD

**Issue by Lenny230809** [GDevelopApp/GDevelop-examples#141]
## Describe the example

Robot TD Example

in this example you can learn how to make a tower defense game with Multiplayer in it. I maked this example for you so when you have Problems by making
a Tower defense Game you can go in this example, In the Example are a Menu,Shop and more The events are under external Events not under the normal the
Singleplayer maps are the Multiplayer Maps too.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

[Project file](https://www.dropbox.com/s/8auke8nhnklkrvw/Tower%20defense%20game.zip?dl=0)

**Comment by D8H** [comment]
Thanks for sharing this example.

Please, copy-paste the content of the readme in the GitHub description.
Maybe drag and drop your tutorial video in the description and lighten the zip from it.

I personally have a really low band-wide to MediaFire. Are you sure you can't drag and drop a zip in the message? Otherwise, try to use another host like Google Drive or Dropbox if you can.

**Comment by Bouh** [comment]
Sorry, here the project files uploaded on dropbox:
https://www.dropbox.com/s/8auke8nhnklkrvw/Tower%20defense%20game.zip?dl=0

**Comment by D8H** [comment]
Objects and variables names doesn't fit the naming conventions. It's hard to read "plusmoneycardtext", it should be "PlusMoneyCardText". Please, rename every objects and variables and read again the good practice guide.

**Comment by Bouh** [comment]
Hi @Lenny230809 
Can you keep us informed of the current state of your example? Is the previous reviews has been applied?
Did you need another review?

**Comment by Lenny230809** [comment]
Yeah im still working but i had vacation so i can't do anything sorry
