### ISSUE TITLE
AI movement example

### ISSUE THREAD

**Issue by RainbowGuy2** [GDevelopApp/GDevelop-examples#147]
## Checklist

- [x] My game has a proper name in the game properties. 
- [ ] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [ ] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

![AI-1](https://user-images.githubusercontent.com/91103087/139271601-2da4d492-5cd5-458e-9d12-36a6f0bebb28.png)
![AI-12](https://user-images.githubusercontent.com/91103087/139271603-88886cc8-9135-4fdf-895e-33b60efb3516.png)
![Darkbrick-1](https://user-images.githubusercontent.com/91103087/139271606-6716286d-50bb-4b33-a394-91eb28d349d4.png)
![King](https://user-images.githubusercontent.com/91103087/139271608-917fb569-fd19-4310-96f0-6093606fade3.png)
![Ladder-1](https://user-images.githubusercontent.com/91103087/139271609-0c553a89-8eba-4ec4-b3cb-d53a2d38b6e4.png)
![Ladder-12](https://user-images.githubusercontent.com/91103087/139271611-4a4aabfc-022f-4e76-b733-7dc3232a0575.png)

**Comment by Bouh** [comment]
Closing because there is no link for testing and reviewing the example.
