### ISSUE TITLE
[New example] Raycast debug view

### ISSUE THREAD

**Issue by Bouh** [GDevelopApp/GDevelop-examples#150]
## Describe the example
Add a raycast debug view in a new example (based on a GD4 example).
![image](https://user-images.githubusercontent.com/1670670/140432498-0d78a33f-342e-4762-8e2b-b123ddbeb2ea.png)

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
[RayCastDebugView.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7492164/RayCastDebugView.zip)

**Comment by Bouh** [comment]
I'll not review my submission, waiting for someone from the example teams ;)

**Comment by Midhil457** [comment]
Hi, here is my review,
- `Player.AngleToPosition(MouseX(),MouseY())` works exactly the same as `ToDeg(atan2(MouseY("",0)-Player.Y(), MouseX("",0)-Player.X()))` and is easier for users to understand
- An empty event
![wmpty](https://user-images.githubusercontent.com/73597906/140635731-12f93ffb-37e4-4401-bd07-29e37873e936.PNG)
- `Rotate` action works as the same as changing angle using timedelta. `Rotate` might be a more preferred
![rotate](https://user-images.githubusercontent.com/73597906/140635806-f20113a4-8554-4773-b67a-8cb258c3d29c.PNG)
- There is a triangle object that is unreachable by he raycast. Is it to show that the raycast can only detect objects in the given range?
![uno](https://user-images.githubusercontent.com/73597906/140635833-899da031-13ad-4e98-8b70-a4781d86dabd.PNG)
 
- `Simple example showing how working the raycast selection.` (README) sounds wrong. `Simple example showing how raycast detects objects.` might be better

:)

**Comment by Bouh** [comment]
> There is a triangle object that is unreachable by he raycast. Is it to show that the raycast can only detect objects in the given range?

Yes.

Changes applied on this version (Updated in first post)
[RayCastDebugView.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7492164/RayCastDebugView.zip)

**Comment by Midhil457** [comment]
Hi, I didn't find any issues and this example could be merged.
- Except for reverting `com.gdexample` to `com.example` Extremely sorry for the mistake :sweat: 

I am not on my original system and don't have git installed or anything. So, it would be great if you could create a PR and merge it :)

**Comment by Bouh** [comment]
Here we go with `com.example.RayCastDebugView`
[RayCastDebugView.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7497020/RayCastDebugView.zip)

**Comment by Midhil457** [comment]
If that’s the only change. I can approve it. I wasn’t able to find any other notable issues :)

> I am not on my regular system and don't have git installed or anything. So, it would be great if you could create a PR and merge it :)

**Comment by Midhil457** [comment]
I have made a PR for merging the example

Thank you

Still don't know how to properly merge PRs :sweat_smile:  (I have seen some PRs being squashed, and also how to make in  visible in the release note, etc...)

**Comment by Midhil457** [comment]
Ah, Thank you for the explanation! I will try doing it from now on

:)

**Comment by Bouh** [comment]
Thank you @Midhil457 :)
