### ISSUE TITLE
New example: Paint

### ISSUE THREAD

**Issue by Jurfix** [GDevelopApp/GDevelop-examples#154]
## Describe the example
A regular paint, the ability to draw free-form lines using Shape Painter, the example implements color change using RGB, reading the pixel color using the Read Pixels extension.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

[Paint.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7497338/Paint.zip)

**Comment by Midhil457** [comment]
Hi,
I found some issues with the example and most of them are mentioned in the best practices. So, I request you to follow the best practices, http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example#best_practices

**Comment by Jurfix** [comment]
> Hi, I found some issues with the example and most of them are mentioned in the best practices. So, I request you to follow the best practices, http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example#best_practices

I have made some changes, the only thing that is difficult for me is to add the correct comments. this example was created for a very long time and works as we say "on crutches")

**Comment by Midhil457** [comment]
Hi, 

> I have made some changes, the only thing that is difficult for me is to add the correct comments. this example was created for a very long time and works as we say "on crutches")

I do understand your point. But, it's important to have comment to make the users understand what's going on. It's also important to have a sturdy project if it has to be added to the example library. You can take your time to fix the issues and comment out things

:)

**Comment by Bouh** [comment]
I'll make changes. I already started to clean the project resources and few events.

**Comment by Jurfix** [comment]
> 

Okay, is action required on my part?

**Comment by Bouh** [comment]
> > 
> 
> Okay, is action required on my part?

Not yet, I started to work on it, but I'll have more time to work on it by the end of the week and the next one.
I plan to merge this example this month among others extensions and examples review.

**Comment by Bouh** [comment]
We can continue on the[ pull request,](https://github.com/GDevelopApp/GDevelop-examples/pull/193) where I listed the changes I made on the example.
