### ISSUE TITLE
the player follows a drawn path

### ISSUE THREAD

**Issue by antom00** [GDevelopApp/GDevelop-examples#157]
## Checklist

- [ ] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [ ] My game has a proper name in the game properties. 
- [ ] My game package name behind with `com.example.`.
- [ ] My game has all events unfolded.
- [ ] I've added myself as the author in the game properties.
- [ ] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [ ] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [ ] I've cleaned unused resources.

## Game folder

[draw-path-to-follow.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7503510/draw-path-to-follow.zip)

<img width="594" alt="Immagine" src="https://user-images.githubusercontent.com/78436835/140899367-c5b29301-f8e2-40c1-848e-463657d2755d.png">

**Comment by antom00** [comment]
[](url
[draw-path-to-follow.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7503505/draw-path-to-follow.zip)
)

**Comment by antom00** [comment]
[](url
<img width="594" alt="Immagine" src="https://user-images.githubusercontent.com/78436835/140899210-2491ae8c-abe3-4348-b2b9-8587f28f4b96.png">
)

**Comment by Midhil457** [comment]
You are requested to follow the checklist given in the issue template. I have updated your post to include the checklist, tick them when you have ensured that your project follows them

**Comment by Midhil457** [comment]
Closing this as the submitter hasn't responed in months
