### ISSUE TITLE
Example of how you can make the background move infinitely as the camera moves.

### ISSUE THREAD

**Issue by Mixen-me** [GDevelopApp/GDevelop-examples#158]
## Example of how you can make the background move infinitely as the camera moves.

This example is a showcase of how you can make a background that moves infinitely as the camera moves but stops moving if the camera stop.

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated into this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
[InfiniteBackgroundLoop.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7834482/InfiniteBackgroundLoop.zip)

**Comment by Midhil457** [comment]
Hi, nice project
- Cut down on the amount of animations of the player. That much is not needed
- Maybe rename the project to `Infinitely Scrolling Background`
- The README can be `Shows how to make an infinitely scrolling background by changing camera position.`

**Comment by Midhil457** [comment]
Is thsi submission still being worked on or has any plans on being worked on? If not, this submission will be closed

**Comment by Mixen-me** [comment]
Oh sorry. I forgot about this. I have did 2 and 3 but about 1, should the Player not change the animation while it moves?

**Comment by Midhil457** [comment]
I was taking about the cutting down on the frames. For the moving animation, some frames are duplicates of others. You can delete the alternate frames and make the frame speed slower. Don't forget to delete those images from the assets folder and so teh resources

**Comment by Mixen-me** [comment]
Alright. I've updated the project file. Is everything fine now?

**Comment by Bouh** [comment]
I added my feedback and review [on this link](https://github.com/GDevelopApp/GDevelop-examples/pull/216).
Please let's continue on the [Pull Request.](https://github.com/GDevelopApp/GDevelop-examples/pull/216)
