### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by NewYoungNigeriaTechnologies** [GDevelopApp/GDevelop-examples#17]
## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [ ] I've added myself as the author in the game properties.
- [ ] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [ ] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [ ] I've cleaned unused resources.

**Comment by arthuro555** [comment]
Hello 👋 

To submit an example you need to send it to us 😉 Please attach your example folder in a zip file to the issue.  
Note also that you need to have all the criteria in the checklist completed for us to review your submission.
