### ISSUE TITLE
Circular Pong

### ISSUE THREAD

**Issue by Mrtubagames** [GDevelopApp/GDevelop-examples#182]
## Describe the example

This example will show you how to make a circular pong game. It could be made into a high score grinding game or turned into a minigame of a larger game.

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
[circlepongexample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7654273/circlepongexample.zip)

**Comment by Midhil457** [comment]
Hi, nice project!

## Review
- he current way the paddle is made to move around is a bit unnessesary. You can use `put around object` action to make the paddle go around the object. And use a variable to chaneg the angle the paddle is at. SOmething like this.
![cp-1](https://user-images.githubusercontent.com/73597906/144737306-ec51c3ee-13e2-4638-abc9-75b0d2536c98.png)
- I suggest adding mouse/touch controls where you can drag the paaddle around. As currently, when the paddle is at the bottom, the controls are inverted.
- Add a comment explaining that the ball as the Destroy outside screen behavior. Some users might get confused.
- Hitting space key to start or a button might be better than moving the paddle as the scene restarts without any delay and the player might still have the movement keys pressed making the game start instantly
- Also make sure to remove the unused resources after the update and also to update the README
- The README has some weird characters and also a indent at the start, please remove it.

:)

**Comment by Bouh** [comment]
I made change on the example.
- Added mobile support
- Anchor behavior on UI
- Clean assets
- Reduce the events
- Add comments
- Readme fix
- Add thumbnail

Let me know if you spot anything else @GDevelopApp/examples-team 
Download the project: [CirclePongExample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7756757/CirclePongExample.zip)
Example to play: https://games.gdevelop-app.com/game-ffc2f614-9d64-41b1-a224-72412f3e229b/index.html

**Comment by Midhil457** [comment]
A few things I found:
- **Unfold all the events**
- **The smallest thing, use `CurrentSceneName()` instead of `Pong`**
![cp-2](https://user-images.githubusercontent.com/73597906/147575978-79ac4947-240b-48cd-a9ac-372771e05748.png)
- **Here the `+90` isn't nesscessary. Just `90` would be fine**

![cp-1](https://user-images.githubusercontent.com/73597906/147575987-442b744b-6a25-4fd4-a41c-4428bd85432f.png)

**Comment by Bouh** [comment]
I made changes and merged in this PR #204
