### ISSUE TITLE
Tic-Tac-Toe

### ISSUE THREAD

**Issue by Jurfix** [GDevelopApp/GDevelop-examples#19]
## Describe the example

An elementary tic-tac-toe example to help you understand instance variables.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

[Tic tac toe.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6750441/Tic.tac.toe.zip)

**Comment by Jurfix** [comment]
You can make the code more optimized by using an object variable instead of a scene variable in order to find in which cell there is a cross and in which zero, but I deliberately left everything like this, because this will help to work online, for example through P2P, I would like to share in the future also an example of tic-tac-toe online through P2P, which I already have and is already working.

**Comment by Bouh** [comment]
I've edited your first post, the content was added between comment tags that make the contents not visible.

**Comment by 4ian** [comment]
Looks good! Adding this to the examples :)

**Comment by Midhil457** [comment]
@4ian sorry to disturb. I am experimenting with making the events better. If you can wait for a day, I can finish it and make a commit to your PR

**Comment by 4ian** [comment]
> @4ian sorry to disturb. I am experimenting with making this events better. If you can wait for a day, I can finish it and make a commit to your PR

Ah sorry the PR got automatically merged, but that's no problem: yes please! :) Please make any improvement and open a new PR for this :)

**Comment by Midhil457** [comment]
I will include the changes in the Event clean up

:)
