### ISSUE TITLE
New thumbnail for example / showcase

### ISSUE THREAD

**Issue by Elairyx7301** [GDevelopApp/GDevelop-examples#201]
The thumbnail of the showcase / example game I, Elairyx, have submitted called
### » Seven Nights At Rikey's
could be improved so I made another thumbnail for it and would kindly ask the team to take this as the new thumbnail for the game . 
Please feel free to resize the image or mention me if something should be wrong or if I should provide a smaller version of the image etc..
Also, I think a moderator can remove the "bug" label since it's not really a bug. (1704x958)

![snar](https://user-images.githubusercontent.com/83909121/147546242-a5385544-10a5-444b-b122-7f92fddb9ef7.png)

Thank you!

**Comment by Bouh** [comment]
The image has been updated, it will be visible in a few hours, let me know (ping me here) if needed.

**Comment by Elairyx7301** [comment]
@Bouh The thumbnail still shows the old image for me. Could it be that it's cached and won't load the new image?

**Comment by Bouh** [comment]
It works :) Yes, maybe a cache problem!
![image](https://user-images.githubusercontent.com/1670670/148295248-cfc832f1-88f0-4c02-a932-5a17820e4344.png)
