### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by Yumel22** [GDevelopApp/GDevelop-examples#209]
## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [ ] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [ ] I've cleaned unused resources.

**Comment by Bouh** [comment]
I close this empty submission without description, link to try the example, and a link to download it.
