### ISSUE TITLE
Top-Down Pushable Block

### ISSUE THREAD

**Issue by Mixen-me** [GDevelopApp/GDevelop-examples#212]
## Top-Down Pushable Block Example
An example showcasing how Tween and Object Points can be used to make a mechanism to push a block in a Top-Down Game.

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
[Pushable Block (4).zip](https://github.com/GDevelopApp/GDevelop-examples/files/7834508/Pushable.Block.4.zip)

**Comment by Midhil457** [comment]
- There is an unimplemented bomb feature, please remove it 
   - Don't forget to remove the variable attached to the object
![bombing](https://user-images.githubusercontent.com/73597906/149665860-be9542a4-8d96-47b9-b87f-2f0f4c62034f.png)

- Two boxes can be merged (be in the same place) which doesn't look good. The player should be able to push multiple boxes

https://user-images.githubusercontent.com/73597906/149665841-76fd1fa7-0a67-4dc2-923e-8a821e821b84.mp4

:)

**Comment by Bouh** [comment]
No news from @Mixen-me to apply fixes, I close.
Feel free to ping me to reopen it if you'll submit an update.
