### ISSUE TITLE
Menu With Tweens (Updated Existing Example)

### ISSUE THREAD

**Issue by Dreamkingmovies** [GDevelopApp/GDevelop-examples#213]
(This Example has already been submitted. I am just added a contribution and some icons) (Existing name: Menu with tweens)

This example shows how to animate menus using the tween behavior.

[MenuWithTweens.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7836819/MenuWithTweens.zip)

Discord: Thewavinace#7960

**Comment by Dreamkingmovies** [comment]
@Bouh

**Comment by Bouh** [comment]
Hi @Dreamkingmovies 

Thanks for your input, but the generate the icon in the application isn't necessary.

But a screenshoot of the preview named **thumbnail.png** in 100x100px is welcome as icon for the example list in GDevelop application.

**Comment by Bouh** [comment]
No news from @Dreamkingmovies   to apply fixes, I close.
Feel free to ping me to reopen it if you'll submit an update.
