### ISSUE TITLE
Drag and drop dress up

### ISSUE THREAD

**Issue by Kodwo69** [GDevelopApp/GDevelop-examples#219]
## Describe the example

An example of a drag and drop dress up game. 
Shows how simple events such as: shape painter, positions, collisions, sizes, etc can be used to create a drag and drop dress up game.

## Checklist

- [x ] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x ] My game has a proper name in the game properties. 
- [x ] My game package name behind with `com.example.`.
- [x ] My game has all events unfolded.
- [x ] I've added myself as the author in the game properties.
- [x ] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x ] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x ] I've cleaned unused resources.

## Game folder

[drag-and-drop-dress-up.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7920612/drag-and-drop-dress-up.zip)

**Comment by Bouh** [comment]
Hi Kodwo69, thanks for taking the time to submit this project.

I will have to reject it because the drag and drop example is too basic, other projects show better functionality and the snapping one.
There are repetitions in the events and they are too repetitive.
The objects have default names and there are too many of them.

**Comment by Kodwo69** [comment]
> Hi Kodwo69, thanks for taking the time to submit this project.
> 
> I will have to reject it because the drag and drop example is too basic, other projects show better functionality and the snapping one. There are repetitions in the events and they are too repetitive. The objects have default names and there are too many of them.

Thanks for the feedback. Anyways, what level of complexity does an example need to be to get accepted? Also I had no idea there were existing examples for a dress up.
