### ISSUE TITLE
shoot bug

### ISSUE THREAD

**Issue by beaufordt** [GDevelopApp/GDevelop-examples#221]
## Checklist

- [ ] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [ ] My game has a proper name in the game properties. 
- [ ] My game package name behind with `com.example.`.
- [ ] My game has all events unfolded.
- [ ] I've added myself as the author in the game properties.
- [ ] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [ ] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [ ] I've cleaned unused resources.

## Game folder

[Top down shooter.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7961542/Top.down.shooter.zip)

**Comment by Midhil457** [comment]
Hi, please complete the checkbox (use [x] to mark the checkbox as done)
Also, there is already a more "complete" top down shooter example
