### ISSUE TITLE
Improved Object Selection example "Drag cats in and out of box"

### ISSUE THREAD

**Issue by tristanbob** [GDevelopApp/GDevelop-examples#226]
## Describe the example

Demonstrate how object picking works by using collision conditions. Provides methods to select instances including "any matching", "any not matching", "all matching", and "none matching".

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

[ObjectPickingExample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8149527/ObjectPickingExample.zip)

## Video 

https://user-images.githubusercontent.com/8879811/155902666-ee0d78f2-e7e4-4cce-b3b6-ed586042b338.mp4

**Comment by tristanbob** [comment]
I don't think I made it clear, but I think this example should replace the existing "Object Selection" example.

https://gdevelop-app.com/game-example/object-selection

**Comment by Bouh** [comment]
I really like the new example but it should not replace the old one because the old one is very simple for a reason:
It goes straight to the point, it is very small and gives the basic concepts without more (Extensions, handle of buttons in game, or any secondary things used to make the example game running.)

Your example is much more detailed and advanced, it will be good in addition or even in second scene of the basic example.
In an "AdvancedObjectPicking" scene.

Also if we can avoid to rename the current example "object-selection" and just import your scene inside it'll be great I think.

**Comment by Midhil457** [comment]
Hi, great example! here is my review:
- The `Are All` and `Are All NOT` shouldn't have a quantity
- Unlock all the objects so that users can easily modify and test out the example.

:)

**Comment by tristanbob** [comment]
> Also if we can avoid to rename the current example "object-selection" and just import your scene inside it'll be great I think.

I agree, we are getting an enormous amount of examples and combining the basic and advanced into one example (using two scenes) is a great idea.  I'll do a PR that combines my scene into the existing one.

**Comment by tristanbob** [comment]
> * The `Are All` and `Are All NOT` shouldn't have a quantity

This is intentional!  I was confused about how object picking works when writing an "all" or "none" logic, and I was shocked to see that they pick zero instances.   I think leaving this as it is will help other discover how to deal with this in their games.

> * Unlock all the objects so that users can easily modify and test out the example.

Yes, I will do that when I submit my PR that adds my example into the existing one.

**Comment by Bouh** [comment]
If you want a review please ask for it :)

**Comment by tristanbob** [comment]
> If you want a review please ask for it :)

Thanks!  I'll see if I can get to this PR on the weekend.

**Comment by tristanbob** [comment]
@Bouh I merged the existing example with my new one here: https://github.com/GDevelopApp/GDevelop-examples/pull/235

Please review my submission on that PR.  Thanks everyone!
