### ISSUE TITLE
Please add my name to the examples

### ISSUE THREAD

**Issue by zatsme** [GDevelopApp/GDevelop-examples#227]
I've not been active with Gdevelop for quite a while but now getting back into it!

My old examples are not showing up as contributions in my profile so could somebody please add for me.

Username is Zat

Examples are Downhill Bike physics demo, Bouncing ball and rope, Geodash and Ragdoll

Thanks in advance :)

Zat.

**Comment by Bouh** [comment]
> Thanks for updating those for me, but I forgot a couple more.
> 
> invaders and screen shake
> 
> Can you add those for me or should I open another issue :/
> 
> Zat.

Done in #231 💯
