### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by AngheloXTx** [GDevelopApp/GDevelop-examples#238]
## Checklist

- [ ] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [YES ] My game has a proper name in the game properties. 
- [YES ] My game package name behind with `com.example.`.
- [YES] My game has all events unfolded.
- [YES] I've added myself as the author in the game properties.
- [NO] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [YES] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [I do not understand] I've cleaned unused resources.

## Game folder
[Pixel Survival.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8381967/Pixel.Survival.zip)

**Comment by AngheloXTx** [comment]
Perú

**Comment by Bouh** [comment]
Hi, we have already multiple platformers and pixel games.
Thank you.
