### ISSUE TITLE
Add lossless compression for image files to reduce project sizes

### ISSUE THREAD

**Issue by Midhil457** [GDevelopApp/GDevelop-examples#24]
I am not sure if this is necessary. Something like https://github.com/marketplace/actions/image-actions can help reduce project sizes. As the examples are now stored externally, this can help reduce load times. There are a lot of images in projects, compressing them can reduce the size drastically. Image quality is not the focus of examples, so it shouldn't be a big deal.

One doubt I have is if it will compress a file multiple times.
Something that runs on every PR unless disabled for some PRs. 

:)

**Comment by 4ian** [comment]
This is a good idea. This can either be a tool run on the `examples` folder (in which case the compression must be lossless) or as part of the script that generate the folder for deployment.

**Comment by Midhil457** [comment]
I experimented with this in one of my repos which had 115 small pixel art assets (32x32 average). and it reduced about 14kb. I used the example script to run it. It seems to only compress files that are not compressed already. And only runs when a PR contains a image.
The highest reduction I got is -65%
I didn't find any difference in quality though,
One asset from the not-a-vania example 
![Compress3](https://user-images.githubusercontent.com/73597906/124383603-fc670500-dcea-11eb-850a-4b9483224820.PNG)


![Compress](https://user-images.githubusercontent.com/73597906/124383579-df323680-dcea-11eb-927e-9e9efb5f057d.PNG)



I would really like to implement it, but I am sure if I am experienced enough with actions to do it 

:)

**Comment by 4ian** [comment]
I've added image-actions :) Thanks for finding this, it's going to be very useful and was very easy to integrate! 

Result so far is: "Compression reduced images by <strong>48.6%</strong>, saving <strong>5.67 MB</strong>.".

This will run automatically on Pull Requests.
