### ISSUE TITLE
escala ball

### ISSUE THREAD

**Issue by esdraslov** [GDevelopApp/GDevelop-examples#244]
## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [ ] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

**Comment by esdraslov** [comment]
[escala ball.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8468689/escala.ball.zip)

**Comment by esdraslov** [comment]
_oi_

**Comment by esdraslov** [comment]
**ee**

**Comment by D8H** [comment]
The zip file contains a web build. It's the project folder that is needed to submit examples.

**Comment by Bouh** [comment]
Closing because This is the Breakout example already in the application.
