### ISSUE TITLE
DONT TOUCH THE CREEPER

### ISSUE THREAD

**Issue by luc301** [GDevelopApp/GDevelop-examples#254]
## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

**Comment by Midhil457** [comment]
Please include the project folder too

**Comment by 4ian** [comment]
You can directly close and lock issues like this - it's 99% of the time the user not knowing that they do :)
