### ISSUE TITLE
Bug with an example - Not-A-Vania

### ISSUE THREAD

**Issue by Silver-Streak** [GDevelopApp/GDevelop-examples#27]
### Describe the bug
Something appears to have gotten broken in my example when it got merged into the main example list. 
I *think* something happened during the process to get it made into a single file?

When loading the example, the main scene just renders all of the debug items, no controls are responsive, and the music doesn't play.

### To Reproduce
1. Open 'Not-A-Vania' example
2. Start the preview.
3. Select start game.
4. Problem will occur.

### Screenshots
 ![image](https://user-images.githubusercontent.com/24237149/124938281-c917c500-dfcd-11eb-8abf-c2f52dbb7758.png)

### Additional context
I have real quickly made a new version with single file mode incase something happened when it was being converted before. I've confirmed this does work as expected, at least for me. I also updated the name to Not-A-Vania - Advanced Platformer Example, so people can find it (Unless it's being added to the game templates list, I'm not sure people would have found it before)

[NAVReduxSingleFile.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6785268/NAVReduxSingleFile.zip)

**Comment by 4ian** [comment]
Good catch, seems this is due to two "unknown" actions:
![image](https://user-images.githubusercontent.com/1280130/124939634-2e38de00-e001-11eb-8379-c1c23a4ac41c.png)

What are supposed to be these actions?

**Comment by Silver-Streak** [comment]
![image](https://user-images.githubusercontent.com/24237149/124939790-092b7780-dfcf-11eb-99b0-952687c54005.png)


Definitely looks like something got corrupted as part of the PR.

**Comment by Midhil457** [comment]
For me, (on the desktop app), none of the mentioned problems occur,
![NAV](https://user-images.githubusercontent.com/73597906/124940928-05780f00-e028-11eb-98a1-a2fe11fe510d.PNG)

Here are the debug events:
![NAVDebug](https://user-images.githubusercontent.com/73597906/124940988-10cb3a80-e028-11eb-9661-b5ab5b1f2a80.PNG)

---
I another thing I noticed, your debug object (htiboxes, etc..) seems to be translucent in the image itself. So, is there any reason for setting their opacity to 125 in the events?

:)

**Comment by Silver-Streak** [comment]
> Here are the debug events:
> ![NAVDebug](https://user-images.githubusercontent.com/73597906/124940988-10cb3a80-e028-11eb-9661-b5ab5b1f2a80.PNG)
> 
> I another thing I noticed, your debug object (htiboxes, etc..) seems to be translucent in the image itself. So, is there any reason for setting their opacity to 125 in the events?
> 
> :)

Yeah, that makes it seem like something's broken (or not designed to work on the web app) with the debugging view. Easy enough to remove (working on this now)

As far as your question: The former was an asset change Arthuro requested for the ease of viewing the scene editor. In-game they're still too opaque when debug objects are enabled, so I still set them to a lower opacity.

**Comment by Silver-Streak** [comment]
Removed the debugging view events: 
[NAVReduxSingleFile.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6785533/NAVReduxSingleFile.zip)

**Comment by Midhil457** [comment]
I am not sure if this is important, but the long project name makes the text overflow here. I guess this is fine?
![Overflow](https://user-images.githubusercontent.com/73597906/124946240-7f11fc00-e02c-11eb-9373-8291fcbcb500.PNG)

**Comment by Silver-Streak** [comment]
Good call. Fixing.

**Comment by Silver-Streak** [comment]
Here we go, "Not-A-Vania - Advanced Platformer" fits just fine even on the minimum width for that panel. 
[NAVReduxSingleFileNameUpdate.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6785556/NAVReduxSingleFileNameUpdate.zip)

**Comment by Silver-Streak** [comment]
> That works great!
> I don't want this to be an another review,
> In this event, DebugGroup contains all the objects that are having their opacity changed, so why don't you use DebugGroup to change all their opacity? I saw that the group includes text objects too, so that is a problem
> 
> If you don't mind, I will be happy to do these changes, if needed
> 
> :)

Different object types use different opacity actions, sadly.

**Comment by Midhil457** [comment]
I have opened a PR. I incremented the version number by 0.0.1, now 2.0.1 (hope you don't mind). I didn't go through the entire project as this has already been reviewed

:)

**Comment by 4ian** [comment]
The Debugger Tools extension was missing in the web-app, I'll be fixing this :)
