### ISSUE TITLE
Achievement System Example

### ISSUE THREAD

**Issue by ikmalsaid** [GDevelopApp/GDevelop-examples#270]
## Describe the example

A simple example to show how easy to implement a simple achievement system that can be benefitted by the players to achieve their accomplishments. While in the menu screens, use your mouse to navigate. While in the game, use your arrow keys to move left and right. In order to jump, press the space bar key.

## Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [X] My game has a proper name in the game properties. 
- [X] My game package name behind with `com.example.`.
- [X] My game has all events unfolded.
- [X] I've added myself as the author in the game properties.
- [X] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [X] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I've cleaned unused resources.

## Game folder

[AchievementSystem_ExampleProject.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8598040/AchievementSystem_ExampleProject.zip)

**Comment by Midhil457** [comment]
Great!
I have opened a PR, it will be merged soon

I have made some changes before adding it, 
- Refactor README
- remove splashscreen BG
- remove `\\` from comments
- Do some small slean ups here and there

Thank you for your contribution
:)

**Comment by ikmalsaid** [comment]
Alright. Noted with thanks! :)
