### ISSUE TITLE
Simple Endless Runner

### ISSUE THREAD

**Issue by ProfuseBug673** [GDevelopApp/GDevelop-examples#280]
## Describe the example

 This Example can be helpful to beginners to Have the Knowledge of what a Endless Runner is about .

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x]I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

[simple-endless-runner.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8670535/simple-endless-runner.zip)

**Comment by Bouh** [comment]
We already have an endless runner with [Dino Run Dino](https://editor.gdevelop.io/?project=https://resources.gdevelop-app.com/examples/run-dino-run/run-dino-run.json)
Thank you
