### ISSUE TITLE
Game Template - TheConvictionOfGunDude - Two separate versions - Desktop and Mobile

### ISSUE THREAD

**Issue by HelperWesley** [GDevelopApp/GDevelop-examples#291]
The game is a cross between the binding of issac and nuclear throne, with sprinkles of originality tossed in.

The game showcases how to use/create a shooting mechanic, upgrades, enemies with varying AI and attack patterns, leaderboards, health bars and other UI elements, multiple scenes, and external events.

The mobile version also demonstrates how to create dual joysticks using the multitouch joystick extension.

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [ ] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

[ConvictionOfGunDude_GithubVersion.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8758603/ConvictionOfGunDude_GithubVersion.zip)

[ConvictionOfGunDude_Mobile_GithubVersion.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8758605/ConvictionOfGunDude_Mobile_GithubVersion.zip)

**Comment by HelperWesley** [comment]
Changed the Submit, reset, and submit score buttons so they highlight when hovered over on the desktop version.

This doesn't make sense on the mobile version, so it didn't get added to that version.

[ConvictionOfGunDude_GithubVersion.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8767394/ConvictionOfGunDude_GithubVersion.zip)

**Comment by HelperWesley** [comment]
![LiluoLogoMobileWithBanner](https://user-images.githubusercontent.com/72082749/170165484-24538d40-0307-4c2b-9a90-fb3bb5868d76.png)
![LiluoLogoWithBanner](https://user-images.githubusercontent.com/72082749/170165487-1ba1ef33-350c-4b4f-84e0-3128988d7ed9.png)


Thumbnails to display in engine on the homepage.

**Comment by tristanbob** [comment]
Closing this issue as work will be continued in the two PRs listed above.
