### ISSUE TITLE
Voice Recognition Example

### ISSUE THREAD

**Issue by planktonfun** [GDevelopApp/GDevelop-examples#322]
## Describe the example

A demo for using voice recognition in gdevelop, useful for a developer looking to make voice based games/apps.

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
[voice-recognition-api.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8953029/voice-recognition-api.zip)

**Comment by Bouh** [comment]
Did you already submitted the extension? If no [start here](https://wiki.gdevelop.io/gdevelop5/extensions/best-practices).

For this example you need to:
- [ ] Be approved in the community extension repository
- [ ] Give a project name meaningful
- [ ] Fill the Game Description
- [ ] If you want the Author field
- [ ] Change the package Name
- [ ] Move all assets in an assets folder (there is actually only one file inside)
- [ ] Give a proper name to the assets

**Comment by planktonfun** [comment]
> * [ ]  Be approved in the community extension repository

sent in https://github.com/GDevelopApp/GDevelop-extensions/pull/499

> * [x]  Give a project name meaningful
> * [x]  Fill the Game Description
> * [x]  If you want the Author field
> * [x]  Change the package Name
> * [x]  Move all assets in an assets folder (there is actually only one file inside)

removed all sprite assets except for the button

> * [x]  Give a proper name to the assets
