### ISSUE TITLE
Endless Runner

### ISSUE THREAD

**Issue by Zomple12** [GDevelopApp/GDevelop-examples#345]
## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

[Endless Runner.zip](https://github.com/GDevelopApp/GDevelop-examples/files/9101838/Endless.Runner.zip)

**Comment by Zomple12** [comment]
![Apple-1](https://user-images.githubusercontent.com/108985801/178726754-de474b5e-2489-4c86-b867-6a1ee1b53790.png)
![BG-1](https://user-images.githubusercontent.com/108985801/178726756-9411174f-7102-41b8-ba13-4e99fab67a9f.png)
![BG-1-1](https://user-images.githubusercontent.com/108985801/178726757-3dbd6008-3423-44f3-9420-76f92045c1bb.png)
![BG-1-1-1](https://user-images.githubusercontent.com/108985801/178726762-99b216ea-38b4-4753-828f-b8dd18fa7dac.png)
![Dead-1](https://user-images.githubusercontent.com/108985801/178726767-d17c5513-dfb1-4f35-99ce-fdd3cc131ca0.png)
![Floor-1](https://user-images.githubusercontent.com/108985801/178726769-e5311c50-fc8d-40f6-8ccd-a7ce007a93ac.png)
![FloorCenter-1](https://user-images.githubusercontent.com/108985801/178726771-a92e00e0-8dd8-4a0c-968f-7481db27b58a.png)
![Grid-1](https://user-images.githubusercontent.com/108985801/178726774-17ea62b2-e2d4-41bf-846f-fb184217b68b.png)
![Muo Jump](https://user-images.githubusercontent.com/108985801/178726776-dee5ebca-4e54-44c6-8b37-cf4f5e4a3828.png)
![Muo ldle](https://user-images.githubusercontent.com/108985801/178726779-66f0addc-9863-4139-9031-685341566b70.png)
[README.md](https://github.com/GDevelopApp/GDevelop-examples/files/9101755/README.md)
[README.txt](https://github.com/GDevelopApp/GDevelop-examples/files/9101757/README.txt)
![Red-1](https://user-images.githubusercontent.com/108985801/178726786-b944fbd7-540d-4e87-8af1-117928174ce8.png)
![Run-1](https://user-images.githubusercontent.com/108985801/178726789-5d3c5787-2171-4e48-8a89-a0868dfea1d7.png)
![Run-2](https://user-images.githubusercontent.com/108985801/178726790-652f95bd-7697-493b-a40d-f1fc5109da46.png)
![Run-3](https://user-images.githubusercontent.com/108985801/178726793-d030df7c-fc47-4d99-b560-a62ed2c63ec2.png)
![Run-4](https://user-images.githubusercontent.com/108985801/178726795-3317a48a-58f0-401e-9b1c-3bec8ab304fa.png)
![Run-5](https://user-images.githubusercontent.com/108985801/178726801-b39de5c8-7c6f-471f-961a-18c16b015f38.png)
![Run-6](https://user-images.githubusercontent.com/108985801/178726804-d187907e-cd3b-4b15-ae93-f965d5bafd25.png)
![Run-7](https://user-images.githubusercontent.com/108985801/178726805-de8c65b4-e47d-467a-94ba-aed52402ef20.png)
![Run-8](https://user-images.githubusercontent.com/108985801/178726807-4f0778e9-268e-4272-8c68-5f20210dd80d.png)
![Run-9](https://user-images.githubusercontent.com/108985801/178726814-31b7b21f-fd15-4c67-aa47-69f45c6e1263.png)
![Run-10](https://user-images.githubusercontent.com/108985801/178726819-dcdb1e4a-6d12-46f7-8e1e-3f4d2da028f4.png)
![Spike-1](https://user-images.githubusercontent.com/108985801/178726820-b7b1b349-6368-4819-8ef6-585cc222e820.png)
![White-1](https://user-images.githubusercontent.com/108985801/178726823-b579bf03-28d0-422b-9bcd-0324c5617e48.png)
![White-2](https://user-images.githubusercontent.com/108985801/178726825-e176f9c8-b13e-4a6e-9bee-84e38cf0eb53.png)
![White-3](https://user-images.githubusercontent.com/108985801/178726827-4b665b21-db4c-433d-a402-cf85411d829a.png)
![White-4](https://user-images.githubusercontent.com/108985801/178726830-7c0014d7-25e7-4397-998c-eb1de5948e75.png)
![White-5](https://user-images.githubusercontent.com/108985801/178726831-8181051e-b2c1-4ad0-94cb-86d98d42699f.png)
![White-6](https://user-images.githubusercontent.com/108985801/178726833-f02e27da-0665-4377-96ac-c780576f4d57.png)
![White-7](https://user-images.githubusercontent.com/108985801/178726834-5b930881-f338-4599-8e4e-b0b23759b8d8.png)
![White-8](https://user-images.githubusercontent.com/108985801/178726837-d5a93cf3-184f-4cf1-92ce-a51d2be5b365.png)

**Comment by Bouh** [comment]
Hello thank you for your submission.
We already have a infinite runner called [Run Dino Run](https://gdevelop.io/game-example/run-dino-run).
![image](https://user-images.githubusercontent.com/1670670/179686618-25a987ab-9e5a-4161-8cac-27be4bf41bc9.png)

You can still [submit you game to be visible in the GDevelop Game Showcase](https://docs.google.com/forms/d/e/1FAIpQLSfjiOnkbODuPifSGuzxYY61vB5kyMWdTZSSqkJsv3H6ePRTQA/viewform)!

**Comment by Zomple12** [comment]
is okay thanks for my submission

**Comment by Zomple12** [comment]
if you want to know more about my game 
Link https://github.com/Zomple12/Endless-Runner
