### ISSUE TITLE
Flappy Bird

### ISSUE THREAD

**Issue by MrFloax** [GDevelopApp/GDevelop-examples#352]
## Describe the example
[Flappy Bird.zip](https://github.com/GDevelopApp/GDevelop-examples/files/9150078/Flappy.Bird.zip)

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

<!--
Finally, attach a zip file containing your game and all its resources (images, sounds, etc...)

You also may have to create an account on GitHub before posting.
If your game is high quality and useful, it will be added to the list of GDevelop community examples.
When you're ready, remove this last paragraph and click on "Submit new issue". Thanks 🙌

**Comment by Bouh** [comment]
Hi and thanks @MrFloax for you project.
We already have one called [Tappy Plane](https://gdevelop.io/game-example/tappy-plane) because of copyright, the game works in the same way as the original Flappy Bird.
