### ISSUE TITLE
Platformer Mystery Block Example

### ISSUE THREAD

**Issue by Mixen-me** [GDevelopApp/GDevelop-examples#36]
## Platformer Mystery Box Example

This is a modified Platformer example with a block added same as **Mystery Block** of **Mario**. 
A simple modification of **Platformer template**.

## Changes

- Added a **Mystery Box** where **Player** can bang their head to get nothing, coin, or an enemy.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated into this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

[PlatformerMysteryBox.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6847545/PlatformerMysteryBox.zip)

**Comment by Midhil457** [comment]
Hi, Nice Example!

- There some unused assets in the resources, remove them from the projects folder and also from the resources list
- There is a mistake, it's mystery not mistrey
![MestreyBox](https://user-images.githubusercontent.com/73597906/125961111-4c1acbaa-f878-48c7-859a-865b1ed5e4b6.PNG)

- I think MysteryBox is a better name than WhatBox
- Initialize the objects variable "item" (if needed)

- Also, please update the README file


:)

**Comment by Mixen-me** [comment]
> Hi, Nice Example!
> 
> * There some unused assets in the resources, remove them from the projects folder and also from the resources list
> * There is a mistake, it's mystery not mistrey
>   ![MestreyBox](https://user-images.githubusercontent.com/73597906/125961111-4c1acbaa-f878-48c7-859a-865b1ed5e4b6.PNG)
> * I think MysteryBox is a better name than WhatBox
> * Initialize the objects variable "item" (if needed)
> * Also, please update the README file
> 
> :)

**Comment by Mixen-me** [comment]
@Midhil457 I did everything you told me to do. Should I remove the previous file or should I leave it there?

**Comment by Midhil457** [comment]
Remove the unused resources from the resources list, see http://wiki.compilgames.net/doku.php/gdevelop5/interface/project-manager/resources#remove_unused_imagesaudiofonts

But, this won’t actually delete the files from project folder, so you will have go to the project folder and manually delete it from there

:)

**Comment by Midhil457** [comment]
Also, I think you accidentally closed this issue

**Comment by Midhil457** [comment]
Hi,

- The resources haven't been removed from the project folder. The files are not removed from the project folder when you remove them from the resources

- There are some audio files, fonts that haven't been added to the game, even though they are present in the project folder,  [scanning them in the resources panel ](http://wiki.compilgames.net/doku.php/gdevelop5/interface/project-manager/resources#scan_for_imagesaudiofontsvideos)should fix it
![my](https://user-images.githubusercontent.com/73597906/126031130-18a77c23-b952-46c8-a215-2a123885d0ff.PNG)

- Some comments still use WhatBox

- Also, I recommend removing features from the platformer template that are not needed for showing the features of the example (The Mystery box)

:)

**Comment by Mixen-me** [comment]
Is it OK now?

**Comment by Midhil457** [comment]
Hi, the resources are still having problems. 
- To make it easier for you, remove the given files from the folder, you don't really need to remove the font, you will need it for the score text
![My3](https://user-images.githubusercontent.com/73597906/126060458-04c20a17-4308-4e9a-bcdb-06d91a69ada2.PNG)

- When I meant by removing unnecessary things, I meant the enemies, checkpoint system, etc.. The score is pretty important to show that the coin from the mystery box works

- Tiny thing, change the scene name to Game and not NewScene
:)

**Comment by Mixen-me** [comment]
> To make it easier for you, remove the given files from the folder, you don't really need to remove the font, you will need it for the score text

Thank you.

> When I meant by removing unnecessary things, I meant the enemies,

I am spawning an enemy from MysteryBox too

> Tiny thing, change the scene name to Game and not NewScene

Thank you

**Comment by Midhil457** [comment]
Hi, everything seems fine, 

> When I meant by removing unnecessary things, I meant the enemies, checkpoint system, etc.. The score is pretty important to show that the coin from the mystery box works

This is still not done, remove the unnecessary things, and also add the score back, it will be useful

- As the scene name has been changed, now all the `change scene` actions use "New Scene" for the scene, Use `CurrentScene()` instead

**Comment by Mixen-me** [comment]
Is it okay now? I have re-implemented the scoring system. I have removed unused assets and the checkpoint system too.

**Comment by Midhil457** [comment]
Hi!
Thank you for taking your time can making an example! It means a lot!

- I have added spaces to the project name and some tiny changes, hope you don't mind

:)

**Comment by Bouh** [comment]
Added into GDevelop by #41
Thanks guys for your time and the reviews <3
