### ISSUE TITLE
Tween Bug with an example

### ISSUE THREAD

**Issue by planktonfun** [GDevelopApp/GDevelop-examples#375]
### Describe the bug
A Tween action doesn't work

### To Reproduce
1. Open [tween-test](https://editor.gdevelop.io/?project=example://tween-test) example
2. Use 
![image](https://user-images.githubusercontent.com/1837825/186333448-dc1e27b7-5fbd-4d99-9374-778f477b1eb4.png)
Action
3. See error in the browser console
![image](https://user-images.githubusercontent.com/1837825/186333518-e19a72a9-8269-48d1-904d-fba46d8e3464.png)

### Additional context
- GDevelop version: Web IDE version

**Comment by Bouh** [comment]
I can't reproduce the bug, the variable tween works on my side:
![image](https://user-images.githubusercontent.com/1670670/186931749-6c61435d-b225-4a58-aae1-c32929a3c408.png)

And there is no error in the console :/

**Comment by planktonfun** [comment]
@Bouh this is for object variables, use scene variables
thanks for the fix!
