### ISSUE TITLE
PIRATE TRESURE PLATFORMER

### ISSUE THREAD

**Issue by MEETDEVELOP13** [GDevelopApp/GDevelop-examples#382]
[TRESURE HUNTER.zip](https://github.com/GDevelopApp/GDevelop-examples/files/9601268/TRESURE.HUNTER.zip.)

EXAMPLES INCLUDES: PLAYER,ENEMIES,ITEMS,HEALTHBARS,SCORE,HEALTH AND POTION SYSTEM WITH ENEMIES KILL,AND OBJECT BLAST EFFECT

**Comment by Bouh** [comment]
Hello
Please follow the format from the readme.
