### ISSUE TITLE
3d example for Gdevelp

### ISSUE THREAD

**Issue by Corroriw1** [GDevelopApp/GDevelop-examples#418]
## Checklist

- [ ] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [ ] My game has a proper name in the game properties. 
- [ ] My game package name behind with `com.example.`.
- [ ] My game has all events unfolded.
- [ ] I've added myself as the author in the game properties.
- [ ] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [ ] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [ ] I've cleaned unused resources.

## Game folder
![Thanks](https://user-images.githubusercontent.com/121037815/208445913-15e4fb8f-8a4c-4d48-b822-da4b482a3a45.png)

![Thanks](https://user-images.githubusercontent.com/121037815/208445800-b6720e52-a2a6-4f5d-bcde-a68a26c46db6.png)

**Comment by Bouh** [comment]
Thank you but I think you missed to upload the project file.
And as the extension isn't yet in the app (people have to download it on Itch.io) we won't upload an example for that in the short term unless the extension appear on the community or reviewed extension list in the game engine.
