### ISSUE TITLE
Upload Download Text Files Example

### ISSUE THREAD

**Issue by planktonfun** [GDevelopApp/GDevelop-examples#419]
## Describe the example

An example on how to use upload/download text extension.
(The current gdevelop only supports desktop version, this one is compatible with browsers)

Can be used for 
 - importing/exporting ingame data.

https://user-images.githubusercontent.com/1837825/208557572-77362fdc-c883-4d53-ac2d-f894135720d3.mp4

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

[upload-download-text-example.zip](https://github.com/GDevelopApp/GDevelop-examples/files/10263829/upload-download-text-example.zip)

**Comment by Bouh** [comment]
Hello thx for the example it works well, can we first get the extension approved?
I didn't see it in the [extension repository](https://github.com/GDevelopApp/GDevelop-extensions/) in Issues or PRs.

**Comment by planktonfun** [comment]
Alright, I was hoping to link the example page to the extension description
