### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by frolics2dio** [GDevelopApp/GDevelop-examples#42]
## Car Physics Joint Demo
A realistic physics car demo that allows you to enjoy testing a car in gdevelop.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
[Car Physics Joint Demo.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6868462/Car.Physics.Joint.Demo.zip)

**Comment by Bouh** [comment]
Hello @frolics2dio thanks you for your submission, can you please edit your post and read the instruction?

I close the submission until the changes are done.

**Comment by frolics2dio** [comment]
Hi, Bouh.
Please check my updated submission, Or should I have to submit it again. I have resolved all issues.
Thank you.

**Comment by Midhil457** [comment]
Hi, great example!
- There is already a physics car example, are you making this to replace it? 

- The README file doesn't have to be that long, just a single sentence that tells what the example does is more than enough
- Use a single tyre image for all the tyres and change it's angle in the editor to offset each tyre
- Don't make the scene name all CAPS
- Don't use CAPS in the package name
- Don't lock the objects in the scene editor
- The `logo.png` should be `thumbnail.png` to show up in the library
- It would be great if the vehicle was controllable, but as it's an example, the current set up is fine
- rename the `.json` file to `car-physics-demo-joint-demo`
- `PascalCase` is recommended for variable names

I have included the suggestions for the events in this project
[Car Physics Joint Demo_with suggestions.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6872025/Car.Physics.Joint.Demo_with.suggestions.zip)

:)

**Comment by frolics2dio** [comment]
Hello Gdevelop,

I am sorry but my intention is not to replace that example. I have not made
this to replace that one. I know that example is better. If you thought
that example is good then I have no problem with this.

Thank you,
Frolics2dio :)

**Comment by Midhil457** [comment]
Hi!, sorry for the late reply

I think this is better than the existing
Also, please check my points and change the project accordingly

:)

**Comment by frolics2dio** [comment]
Hello Dear Leo Red,

No worries. Thank you very much for replying.

I will definitely fix all these issues and also add some more functionality
to this example and then send it to you for review in near future.

Thank you,
Frolics2dio :)

**Comment by 4ian** [comment]
Thanks @frolics2dio for submitting this and @Midhil457 for reviewing. looking forward to have this submitted!

**Comment by frolics2dio** [comment]
Glad you like it!
