### ISSUE TITLE
Crazy Games API example

### ISSUE THREAD

**Issue by planktonfun** [GDevelopApp/GDevelop-examples#430]
## Describe the example

Allows developer to use CrazyGames API e.g. displaying ads, invite links, happy time, adblock detection.

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

[crazy-games-api-example.zip](https://github.com/GDevelopApp/GDevelop-examples/files/10367320/crazy-games-api-example.zip)

**Comment by Bouh** [comment]
The extension has changed, there is just to update the example with the approved extension available in the engine and I could approve this example, which is very simple and useful to understand how to use the Crazy Game API!
Thank you @planktonfun !

**Comment by Bouh** [comment]
Thanks for the example, I improved the example and added feature to the extension, it can be used at this link:
https://gdevelop.io/game-example/free/crazygames-sdk-demo
