### ISSUE TITLE
Simple clicker game example.

### ISSUE THREAD

**Issue by ghost** [GDevelopApp/GDevelop-examples#46]
## Checklist

- [x] My game has a proper name in the game properties. (Yes)
- [x] My game package name behind with `com.clickergame.`.
- [x] My game has all events unfolded. (Yes)
- [x] I've added myself as the author in the game properties. (Yes)
- [ ] I've included a file called "README.md" with a description in proper English, explaining what this example is doing. (No)
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed. (Yes i confirm that.)
- [x] I've cleaned unused resources. (Yes)

## Game folder
[Clicker game.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6886660/Clicker.game.zip)

**Comment by Midhil457** [comment]
Hi grif

If you are having trouble adding a README.md file see [Additional things in this page](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example#submitting_the_example)

Also, this example can't really differentiated from the `button` example, the only difference being that there is a text that counts the clicks. The example could show somethings that are special to clicker games, not saying the example should be complicated. The example could help shows things that are key for clicker games. Game feel, some kind of gain, etc...

:)

**Comment by Bouh** [comment]
Closing this due to non-response after 30days.

@ghost if you are still interested in adding this, please apply the reviews and I'll reopen this feed.
