### ISSUE TITLE
Platformer Ai Example

### ISSUE THREAD

**Issue by Mrtubagames** [GDevelopApp/GDevelop-examples#49]
## Platformer Ai Example
A simple platformer with AI entities. It could be friendly or an enemy. It also includes the flashing extension and damage that uses it.

 By following this example, many NPCs can be made. With some ingenuity, it could be molded into other elements of platformers like moving collectibles. It also can show how to take damage, which can be applied to many hazards, even in games that are not platformers.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

[Platformer AI.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6911865/Platformer.AI.zip)

**Comment by Midhil457** [comment]
Hi, great example, I wasn't able to find much issues
But, here are some tiny ones

- The short description `This example shows how to make AI for a platformer.` could be `An simple platformer with AI enemies` to make it similar to all other example's descriptions

- I am not sure if ` Note: I just borrowed this code. It's from this example: https://silver-streak.itch.io/gd5-metroid-camera
` is necessary, but I feel free to keep it

:)

**Comment by Mrtubagames** [comment]
> Hi, great example, I wasn't able to find much issues
> But, here are some tiny ones
> 
> * The short description `This example shows how to make AI for a platformer.` could be `A simple platformer with AI entities` to make it similar to all other example's descriptions
> * I am not sure if `Note: I just borrowed this code. It's from this example: https://silver-streak.itch.io/gd5-metroid-camera` is necessary, but I feel free to keep it
> 
> :)

Thanks! I will fix it as soon as I can.

**Comment by Mrtubagames** [comment]
@Midhil457 I fixed the stuff you noticed.

**Comment by Midhil457** [comment]
Hi, excellent! I have made a pull request for it and should be added to the library when it gets merged

Thanks for taking your time and making a great example!

:)

**Comment by 4ian** [comment]
This looks great! Thanks both :) It should be available in a few minutes.
