### ISSUE TITLE
Some games are named "Game"

### ISSUE THREAD

**Issue by arthuro555** [GDevelopApp/GDevelop-examples#6]
### Describe the bug
Some examples are named "Game"

![image](https://user-images.githubusercontent.com/19349038/121048968-905eb300-c7b7-11eb-90b0-56c53307e51e.png)
![image](https://user-images.githubusercontent.com/19349038/121049015-9d7ba200-c7b7-11eb-8c60-a60798321b18.png)
![image](https://user-images.githubusercontent.com/19349038/121049057-a79da080-c7b7-11eb-927e-d3b3ccfd2503.png)

### To Reproduce
1. Open the examples library
2. Scroll until you see a game named "Game"

### Additional context
- GDevelop version: web-ide

**Comment by Bouh** [comment]
My bad, it's because the name come from the **game.json** I have to rename files.
I'm on it!
