### ISSUE TITLE
Resources not loaded for Break-out example

### ISSUE THREAD

**Issue by Midhil457** [GDevelopApp/GDevelop-examples#65]
### Describe the bug
I was looking at the break-out example and it seems that the resources are not downloaded, The assets are non-existent in the resources. But, the assets are present in the repo.

I tested it with other examples, and it seems to work fine and the issue is not present

### To Reproduce
1. Open the breakout example
2. Open a scene or the resources panel
3. See that no assets are present

### Screenshots
The scene:
![br_1](https://user-images.githubusercontent.com/73597906/128857655-fb3d5a02-9f4c-46fc-a277-d60ced0e1c95.PNG)

The resources:
![br_2](https://user-images.githubusercontent.com/73597906/128857680-a3541a6c-53c3-44af-8509-5adabfc007d0.PNG)

The folder:
![br3](https://user-images.githubusercontent.com/73597906/128857724-1e9981bc-572c-4f03-8501-3cceadb0f287.PNG)

### Additional context
- GDevelop version: beta114, also tested on the web app, same issue

**Comment by Bouh** [comment]
I'm pretty sure I had bundled the project with its resources. I don't know why all the resources disappeared.
I'll add resources, again.
