### ISSUE TITLE
3d block procedural generation example

### ISSUE THREAD

**Issue by Kravataf** [GDevelopApp/GDevelop-examples#678]
## Describe the example

this example generates basic terrain using cubes, there are seeds which determine how the terrain will look like.. (its made using the native 3d) and i added basic fps controller so the player can fly around the terrain, pressing R will reset the scene (on beginning theres random seed each time but that can be changed) also the terrain has size (50x50 blocks by default but can be changed inside of the eventsheet)

## Checklist

- [x] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example).
- [x] My game has a proper name in the game properties.
- [x] My game package name begins with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
[3dblockproceduralgeneration.zip](https://github.com/user-attachments/files/16616337/3dblockproceduralgeneration.zip)

**Comment by Kravataf** [comment]
also to snap the blocks to the grid on the z (elevation) axis the z of each block should be set to ```roundTo(block.noiseColor*2,-2)``` (in the example its ```block.noiseColor```) not snapping to the grid makes it more smooth

**Comment by Clyders** [comment]
NumberVariable extension is missing bruh...

**Comment by Kravataf** [comment]
i found a lot better way to make the generation so im probably going to remake the example from scratch..

**Comment by NOTTwistedDreamz** [comment]
How's the "better way" going? I'm wanting to use this for a Minecraft like game in GDevelop 5
