### ISSUE TITLE
Minesweeper-like game

### ISSUE THREAD

**Issue by tristanbob** [GDevelopApp/GDevelop-examples#68]
~~**Note:** This is a work in progress that is 90% complete.   It needs the logic to clear all neighboring tiles when a user clicks on an empty tile.  I'm asking for help on the GDevelop forum, so please help if you can!~~

## Describe the example

A simple example game similar to Minesweeper.

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

~~[MinesweeperExample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6987365/MinesweeperExample.zip)~~

## Playable game

~~https://games.gdevelop-app.com/game-077ea6e2-2977-4e0f-ab4d-36eca9cc038c/index.html~~

**Comment by tristanbob** [comment]
## Version 1.0.0

Thanks to Alaska for contributing a method to reveal empty tiles by placing a "tester" sprite and checking for collisions.  It is quite simple and effective, and a unique way to solve this problem that is normally done via recursion.

This example is ready to be reviewed!

## Project folder

[MinesweeperExample.zip](https://github.com/GDevelopApp/GDevelop-examples/files/6988527/MinesweeperExample.zip)

## Playable demo

https://games.gdevelop-app.com/game-5d61fbc3-abdf-40e3-a7eb-99b63de1e1fe/index.html

**Comment by Midhil457** [comment]
Hi, I checked out the example for a brief second, and I think something is wrong

This is the only layout I get, just in different positions. From the small amount of minesweepers I have played, I think this is not right how it should be
![mw1](https://user-images.githubusercontent.com/73597906/129533062-a954e09b-3e0c-473c-87ac-ae65c15c45cf.PNG)

**Comment by Bouh** [comment]
It's so cool, I'll review this example tomorrow.
I'll also update graphics style with font and colors from Ping pong example recently added for a visual consistency :)

**Comment by Bouh** [comment]
Continue on #74
