### ISSUE TITLE
New example: City Builder

### ISSUE THREAD

**Issue by D8H** [GDevelopApp/GDevelop-examples#69]
This example shows how to evaluate distance by roads to define rules for city builders.

This example use these extensions:
 * an updated Linked Object Tool that allows to get the distance and combine several search to build complex rules (https://github.com/4ian/GDevelop-extensions/issues/144).
 * the Isometry Helper to snap objects on a grid (https://github.com/4ian/GDevelop-extensions/issues/102)
 * the Mouse Movement without any change (https://github.com/4ian/GDevelop-extensions/issues/123)

The original discussion: https://github.com/4ian/GDevelop/issues/2638

![CityBuilder](https://user-images.githubusercontent.com/2611977/117895318-6603fd80-b2be-11eb-8cd8-e00c69821f83.png)

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder

* download it: https://www.dropbox.com/s/6wwjfg75pyqm1qz/CityBuilder.zip?dl=1
* try it: https://games.gdevelop-app.com/game-143f99ba-13aa-4378-b1c3-50ce38efbb20/index.html

**Comment by Midhil457** [comment]
Great, 
I created a PR for this. I made a separate comment for the help link

Thank you for taking your time and making this example :)

**Comment by Bouh** [comment]
Let's continue to talk on the pull request :)
