### ISSUE TITLE
Admob Template Not Working For All Types

### ISSUE THREAD

**Issue by zawawimanja** [GDevelopApp/GDevelop-examples#691]
### Describe the bug

Ads not shown in all types of ads in exported apk. I already using test ads and using other apk that build not from gdvelop and its ads is display.

### Expected Result
Ads shown

### Actual Result
Ads not shown.

### Additional context

- GDevelop version: '5.4.209'

**Comment by 4ian** [comment]
We have multiple people in the community using successfully ads including in the latest version. This is probably a case of needing to either wait for your account to be ready on Admob side or some configuration. Please open a thread on the forum, I'm going to close this as there is no proven bug that can be reproduced from a project :)
