### ISSUE TITLE
Yarnalia - Yarn dialog with NPC avatars & quests template

### ISSUE THREAD

**Issue by UlisesFreitas** [GDevelopApp/GDevelop-examples#73]
## Yarn dialogs, with NPC avatar & quest
Talk with the NPCs inside the castle room to solve some quests they give to you, this example demonstrate how easily you can setup a Yarn dialog into GDevelop.

Controls:
Z - Talk/interact with NPC
Arrows -  to move
Space - jump

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

## Game folder
https://games.gdevelop-app.com/game-215691d5-7da2-4b3a-a992-9907cdfdb557/index.html

Finally, attach a zip file containing your game and all its resources (images, sounds, etc...)
https://gamesigniter.com/yarnalia/yarnalia.zip

You also may have to create an account on GitHub before posting.
https://github.com/UlisesFreitas/Yarnalia-GDevelop-example

**Comment by Bouh** [comment]
I was reviewing the game. I didn't know why the "run" animation is not triggered.
I've compared with the platformer, deleted all non-related events for kept the strict minimum. I've also deleted the event and remade it. But nope "run" animation is a mystery.

**Comment by UlisesFreitas** [comment]
Let me check

**Comment by Bouh** [comment]
The feet of the player don't move, the run animation is not triggered.
On your playable link, and in the zip file.




https://user-images.githubusercontent.com/1670670/129923337-eb2f10a6-6a95-4e69-8c37-7c25e0414fdd.mp4

**Comment by UlisesFreitas** [comment]
Well I don't know what is failing in my itch.io is working as you can see the downloaded project from the Github repo is working too
Sorry the quality is still processing hd
https://www.youtube.com/watch?v=Za66DuKZd9U

**Comment by Bouh** [comment]
- The problem is still here for me, however, it's not a big deal if this happens only to me.
- When we approach the signs we don't know which key to use for reading. It's explained once you read the sign. A bit too late isn't?
Same for all other interactions.
- Try to fit the best practice guide for: Object names, animation names, 
- Ashley's name isn't really readable in blue try another color.
- Golden Key color is khaki, a more yellowed is welcome for THE gold key ;)
- In some MMOs there is an interrogation mark on top of NPC to mark an available quest, you think you can do that?

**Comment by UlisesFreitas** [comment]
updated the version to 1.0.1
Deleted all icons since there is no relevance in this
Renamed almost all i could to camelCase
Edited the color in dialogs all very good visible now Ashley is Green now and the key yellow
Changed the kaki to yellow in the key (WTF was the problem with the golden key I don't know gold is gold)
Added  a [Z] button to the PlayerHitBox following position and it will appear when hi collides with signs or NPC
The exclamation signs are those really needed I mean there are 3 NPC and 2 signs Unless the player want to talk with walls there is no point in that.
Anyway the project is updated if this version is not good enough to be included just close the issue.

Here the playeable: https://games.gdevelop-app.com/game-f9420e6d-3a53-447b-9abf-07f74559dc47/index.html
Here the latest version: 1.0.1:  [dialogalia-1.0.1.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7085653/dialogalia-1.0.1.zip)
Here the GitHub: 1.0.1: https://github.com/UlisesFreitas/Yarnalia-GDevelop-example

**Comment by Bouh** [comment]
@UlisesFreitas Added in #84 
Renamed to Yarnalia to be consistent with Yarn dialog system. Dialog was too generic.
Thumbnail added
Description in Readme rewrote.
