### ISSUE TITLE
Guide for submitting examples

### ISSUE THREAD

**Issue by Bouh** [GDevelopApp/GDevelop-examples#76]
# ➡️ [See the best practices for submitting examples](http://wiki.compilgames.net/doku.php/gdevelop5/community/guide-for-submitting-an-example) ⬅️

**Comment by Midhil457** [comment]
This link directs to the **extension** best practices. Or is it intentional?

**Comment by esdraslov** [comment]
my texple: [game ball new.zip](https://github.com/GDevelopApp/GDevelop-examples/files/8468733/game.ball.new.zip)
