### ISSUE TITLE
Rhythm example details also shown in description

### ISSUE THREAD

**Issue by Midhil457** [GDevelopApp/GDevelop-examples#90]
The details and description is seperated by a empty line. Which is how all the example with a details given does. But, it doesn't work  for this example. Is it because of the `.` at the end of the description?

![Screenshot from 2021-09-05 20-02-48](https://user-images.githubusercontent.com/73597906/132130733-4bf857e3-cb83-4b5d-8ed2-08b5ddfb0009.png)

**Comment by 4ian** [comment]
Good catch! This is because the README.md was using Windows line terminators. I've fixed the script generating the descriptions to handle this!
