### ISSUE TITLE
Inaccurate search results

### ISSUE THREAD

**Issue by Midhil457** [GDevelopApp/GDevelop-examples#91]
When `lights` is searched, `forward camera` example is one of the result even though light has nothing to do with that example. There might be more of this type, but I didn't find them in my quick search

![lights](https://user-images.githubusercontent.com/73597906/132130901-80e3a68a-d8d2-40d3-ab9d-ab6918ff9e32.png)

**Comment by 4ian** [comment]
This was working as intended :) There was a useless "light obstacle" behavior in the Forward Camera example. I've removed it!
