### ISSUE TITLE
Complex Animation Attack combo and Dash

### ISSUE THREAD

**Issue by Ajgamerteam** [GDevelopApp/GDevelop-examples#95]
## Describe the example how to implement attack combo dashing slide with there animation

 how to implement attack combo dashing slide with there animation using 

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "[Complex animation.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7149413/Complex.animation.zip)
[Complex animation.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7149415/Complex.animation.zip)
" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

**Comment by Bouh** [comment]
Closing same as https://github.com/GDevelopApp/GDevelop-examples/issues/96
