### ISSUE TITLE
Complex Animation with Attack Combo and Dash

### ISSUE THREAD

**Issue by Ajgamerteam** [GDevelopApp/GDevelop-examples#96]
## Describe the example
Complex animation including attack combo, dash, sliding, air dash, with gamepad and keyboard.

## Checklist

- [ ] My game has a proper name in the game properties. 
- [ ] My game package name behind with `com.example.`.
- [ ] My game has all events unfolded.
- [ ] I've added myself as the author in the game properties.
- [ ] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [ ] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [ ] I've cleaned unused resources.

## Game folder
[StateMachineCombo.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7609486/StateMachineCombo.zip)

**Comment by Bouh** [comment]
I'm not convinced by the example, I'm not for adding it.
It looks like a low-quality example, the Not-A-Vania example is more complete and uses [FSM](http://wiki.compilgames.net/doku.php/gdevelop5/tutorials/finite_state_machine#how_to_handle_complex_logic_the_finite_state_machine_fsm).

**Comment by Ajgamerteam** [comment]
Well it is an example for Animation plus it is an example not a game so i don't understand your standered about low quality and high quality the examples ARE NOT GAMES so they have to show a specific topic not using free asstes from itchio and call it complete Plus i don't seem to recall Not-A-vania having combo attack However suit yourself if you want me to add something suggest something

**Comment by Bouh** [comment]
As nobody seems to be very warm to give his help I take back the hand.
I reopened the example and it convinced me, movements and beautiful animations.

So here is the list of things to improve:

## Review
- Enable the nearest mode in-game properties for a pixel art game.
- Disable smooth on all sprites in the resources tab.
- Remove all unused resources (there is a lot of unused images)
- I recommend using [an FSM system](https://wiki.compilgames.net/doku.php/gdevelop5/tutorials/finite_state_machine) it makes the event sheet cleaner and the game state are just better with it.
- While you press C we can move, but the Player is crouch. Just disable movement if C is pressed, or find a walking crouch animation for it.
- Same for X
- Add on the scene a small text explaining which inputs the Player can use.
- Add limit on the world, the Hero can fall and the scene doesn't restart :| 
- You use a lot of the action 'Animation by the number', instead use the animation by name it makes the events cleaner and understandable.
- Object  `platform` to `Platform`.
- All resources should be in an `assets` folder.
- the readme is currently `README.md.txt`, => "README.md"
- The content in the readme change to `This example shows you how to implement complex animation and how to add attack combo dashing and slide animation.`
- On the Player object, you have empty animations, remove all the empty things in general.
- If you use version 5.0.120 please add your nickname in Authors in-game properties.
- I can see you use the Health extension, but the Player can't be damaged, something like spikes could be added. or something else that damage the Player.

**Comment by Ajgamerteam** [comment]
Hey Bouh Thank you for the suggestion I will implement them as soon as possible

**Comment by Bouh** [comment]
Cool! I dug into your repository and found this version:
[StateMachineCombo.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7609486/StateMachineCombo.zip)

It's a lower version than on your video, I didn't find a more recent one, but it is already very complete!
Just need to clean a bit and fit the best practice guide, and here we go 🚀

**Comment by Midhil457** [comment]
Does this submission need a review?

**Comment by Bouh** [comment]
> Does this submission need a review? or is this still wip?

Yes I think.

**Comment by Midhil457** [comment]
I'll try to do a proper review this weekend :)
- Unfold all events
- Properly comment the events
- The project doesn't work on mobile, so I don't see the point in having icons for mobile platforms
- The minimum FPS is set below 20, which could bring some issues?
- In the splashscreen, `description1`, `description2`, etc.. could be given more meaningful names that correspond to their use

:)

**Comment by Midhil457** [comment]
I forgot about this 😅,
- Some variavles could be converted to bools to simplify things
- Typo: `Couch` -> `Crouch` Group name `PlayerEvents` external events
- Variables `PositionX` and `PositionY` seem to be unused
- `obj_floor_collidion` seem to be unused
- There are some instances that seem to be unused
![un](https://user-images.githubusercontent.com/73597906/154680088-bcb9d5c5-64a4-4e23-9232-5f7c135447d5.png)

:)

**Comment by Bouh** [comment]
Closed for inactivity, we could reopen the submission if someone applies the changes request in all lists above.
Thank you all.
