### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by Ajgamerteam** [GDevelopApp/GDevelop-examples#97]
[Complex animation.zip](https://github.com/GDevelopApp/GDevelop-examples/files/7149417/Complex.animation.zip)

## Describe the example You can implement complex animation for attack combo and dash

You Can implement complex animation including attack combo Dash slide using invert conditions and sub events

## Checklist

- [x] My game has a proper name in the game properties. 
- [x] My game package name behind with `com.example.`.
- [x] My game has all events unfolded.
- [x] I've added myself as the author in the game properties.
- [x] I've included a file called "README.md" with a description in proper English, explaining what this example is doing.
- [x] I confirm that this game and all of its resources can be integrated to this GitHub repository, distributed and MIT licensed.
- [x] I've cleaned unused resources.

**Comment by Bouh** [comment]
I'm not convinced by the example, I'm not for adding it.
It looks like a low-quality example, the Not-A-Vania example is more complete and uses [FSM](http://wiki.compilgames.net/doku.php/gdevelop5/tutorials/finite_state_machine#how_to_handle_complex_logic_the_finite_state_machine_fsm).
